version: '3.8'

services:
  db:
    image: postgres:15
    container_name: join-match-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: superpass
      POSTGRES_DB: joinmatch
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
